### ISSUE TITLE
concurrent map writes, only on AWS?

### ISSUE THREAD

**Issue by domino14** [domino14/liwords-socket#1]
```

2020-09-27T00:22:07.047-04:00	fatal error: concurrent map writes	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.047-04:00	fatal error: concurrent map writes	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 55232 [running]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	runtime.throw(0x94262c, 0x15)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc0000cf940 sp=0xc0000cf910 pc=0x4377b2	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	runtime.mapassign_fast64ptr(0x8bb940, 0xc00010e4e0, 0xc0001c6230, 0xc000183b48)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/map_fast64.go:266 +0x332 fp=0xc0000cf980 sp=0xc0000cf940 pc=0x414992	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Hub).addToRealm(0xc00006e4b0, 0x93c5f5, 0x5, 0xc0001c6230)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/hub.go:251 +0x19d fp=0xc0000cfa10 sp=0xc0000cf980 pc=0x859bdd	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.registerRealm(0xc0001c6230, 0xc0001e80c5, 0x1, 0xc00006e4b0, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/hub.go:309 +0x425 fp=0xc0000cfaa0 sp=0xc0000cfa10 pc=0x85ab05	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.ServeWS(0xc00006e4b0, 0x9cff40, 0xc0001da460, 0xc0000c2700)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/client.go:225 +0x425 fp=0xc0000cfb38 sp=0xc0000cfaa0 pc=0x857fc5	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	main.main.func1(0x9cff40, 0xc0001da460, 0xc0000c2700)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/cmd/socketsrv/main.go:54 +0x48 fp=0xc0000cfb68 sp=0xc0000cfb38 pc=0x85d768	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.HandlerFunc.ServeHTTP(0xc000116620, 0x9cff40, 0xc0001da460, 0xc0000c2700)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2042 +0x44 fp=0xc0000cfb90 sp=0xc0000cfb68 pc=0x6b81e4	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.(*ServeMux).ServeHTTP(0xc7b600, 0x9cff40, 0xc0001da460, 0xc0000c2700)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2417 +0x1ad fp=0xc0000cfbf0 sp=0xc0000cfb90 pc=0x6ba10d	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.serverHandler.ServeHTTP(0xc0001121c0, 0x9cff40, 0xc0001da460, 0xc0000c2700)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2843 +0xa3 fp=0xc0000cfc20 sp=0xc0000cfbf0 pc=0x6bb7e3	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.(*conn).serve(0xc0001221e0, 0x9d0dc0, 0xc00026a5c0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:1925 +0x8ad fp=0xc0000cffc8 sp=0xc0000cfc20 pc=0x6b6fed	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	runtime.goexit()	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000cffd0 sp=0xc0000cffc8 pc=0x46bd81	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by net/http.(*Server).Serve	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2969 +0x36c	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 1 [IO wait]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.runtime_pollWait(0x7fe6e0612e88, 0x72, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/netpoll.go:220 +0x55	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*pollDesc).wait(0xc0000bc618, 0x72, 0x0, 0x0, 0x93cdcb)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*pollDesc).waitRead(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*FD).Accept(0xc0000bc600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_unix.go:394 +0x1fc	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net.(*netFD).accept(0xc0000bc600, 0x3fb7c357b573a141, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/fd_unix.go:172 +0x45	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net.(*TCPListener).accept(0xc00000f1e0, 0x5f70136f, 0xc000144d68, 0x48ade6)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net.(*TCPListener).Accept(0xc00000f1e0, 0xc000144db8, 0x18, 0xc000000180, 0x6bbcac)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/tcpsock.go:261 +0x65	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.(*Server).Serve(0xc0001121c0, 0x9cfcc0, 0xc00000f1e0, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2937 +0x266	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.(*Server).ListenAndServe(0xc0001121c0, 0xc0001121c0, 0x3)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:2866 +0xb7	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net/http.ListenAndServe(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/http/server.go:3120	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	main.main()	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/cmd/socketsrv/main.go:56 +0x2a8	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 18 [select]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Hub).PubsubProcess(0xc00006e4b0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/pubsub.go:61 +0x30f	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/domino14/liwords-socket/pkg/hub.(*Hub).Run	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/hub.go:166 +0x57	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 7 [IO wait]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.runtime_pollWait(0x7fe6e0612f68, 0x72, 0x9c9980)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/netpoll.go:220 +0x55	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*pollDesc).wait(0xc0000bc498, 0x72, 0xc0001a2000, 0x8000, 0x8000)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*pollDesc).waitRead(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	internal/poll.(*FD).Read(0xc0000bc480, 0xc0001a2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1b1	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net.(*netFD).Read(0xc0000bc480, 0xc0001a2000, 0x8000, 0x8000, 0x4a, 0xc00019c000, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/fd_posix.go:55 +0x4f	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	net.(*conn).Read(0xc000186000, 0xc0001a2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/net/net.go:182 +0x8e	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/nats-io/nats%2ego.(*Conn).readLoop(0xc0000aeb00)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2144 +0x11b	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1489 +0x197	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 8 [chan receive]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/nats-io/nats%2ego.(*Conn).flusher(0xc0000aeb00)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2392 +0xef	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1490 +0x1b9	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 9 [sync.Cond.Wait, 1814 minutes]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	runtime.goparkunlock(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/proc.go:312	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	sync.runtime_notifyListWait(0xc000063b90, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/sema.go:513 +0xf8	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	sync.(*Cond).Wait(0xc000063b80)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/sync/cond.go:56 +0x9d	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/nats-io/nats%2ego.(*asyncCallbacksHandler).asyncCBDispatcher(0xc00000ef00)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2067 +0x35	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/nats-io/nats%2ego.Options.Connect	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1074 +0x217	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 10 [running]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine running on other thread; stack unavailable	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by main.main	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/cmd/socketsrv/main.go:42 +0x194	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 71 [sync.Cond.Wait, 4 minutes]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	runtime.goparkunlock(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/proc.go:312	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	sync.runtime_notifyListWait(0xc000190850, 0xc000000022)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/runtime/sema.go:513 +0xf8	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	sync.(*Cond).Wait(0xc000190840)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/usr/local/go/src/sync/cond.go:56 +0x9d	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0000aeb00, 0xc0001fe000)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2178 +0x425	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:3048 +0x494	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 55249 [runnable]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Client).readPump(0xc0001c6230)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/client.go:86	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/domino14/liwords-socket/pkg/hub.ServeWS	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/client.go:223 +0x3f5	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	goroutine 55248 [runnable]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Client).writePump(0xc0001c6230)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/client.go:126	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	created by github.com/domino14/liwords-socket/pkg/hub.ServeWS	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.055-04:00	/opt/program/pkg/hub/client.go:222 +0x3d3	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	goroutine 10 [running]:	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	runtime.throw(0x94262c, 0x15)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc000048d40 sp=0xc000048d10 pc=0x4377b2	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	runtime.mapassign_fast64ptr(0x8bb940, 0xc00010e4e0, 0xc0001c6230, 0x0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/usr/local/go/src/runtime/map_fast64.go:266 +0x332 fp=0xc000048d80 sp=0xc000048d40 pc=0x414992	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Hub).addClient(...)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/opt/program/pkg/hub/hub.go:85	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	github.com/domino14/liwords-socket/pkg/hub.(*Hub).Run(0xc00006e4b0)	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/opt/program/pkg/hub/hub.go:170 +0x7fb fp=0xc000048fd8 sp=0xc000048d80 pc=0x8598bb	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	runtime.goexit()	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000048fe0 sp=0xc000048fd8 pc=0x46bd81	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	created by main.main	ecs/liwords-socket/5035498b-bd40-4a2e-9f6c-23efc215b5bb

2020-09-27T00:22:07.063-04:00	/opt/program/cmd/socketsrv/main.go:42 +0x194
```

**Comment by domino14** [comment]
this was fixed; code deployed was old ._.
